# apiVersion: v1
# kind: Pod
# metadata:
#  name: static-web
#  namespace: hello-namespace
#  labels:
#    role: nginx
# spec:
#  containers:
#    - name: web
#      image: nginx
#      ports:
#        - name: web
#          containerPort: 80
#          protocol: TCP


apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-deployment
 namespace: hello-namespace
spec:
 selector:
   matchLabels:
     app: hello
 replicas: 3
 template:
   metadata:
     labels:
       app: hello
   spec:
     containers:
     - name: hello
       image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0"