apiVersion: v1
kind: Pod
metadata:
 name: static-web
 namespace: mesa4
 labels:
   role: nginx
spec:
 containers:
   - name: web
     image: nginx
     ports:
       - name: web
         containerPort: 80
         protocol: TCP